# Generated by Django 3.2.12 on 2023-03-07 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostNft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('EDITING', 'Editing'), ('REQUESTED', 'Requested'), ('PROCESSING', 'Processing'), ('MINTED', 'Minted'), ('TRANSFERED', 'Transfered')], default='EDITING', max_length=32)),
                ('access', models.CharField(blank=True, choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=32)),
                ('creator', models.CharField(blank=True, max_length=164, null=True)),
                ('collection', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[500, 500], upload_to='images')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos')),
                ('internal_id', models.CharField(blank=True, max_length=32, null=True)),
                ('contract', models.CharField(blank=True, max_length=64, null=True)),
                ('chain', models.CharField(blank=True, default='FLOW', max_length=64, null=True)),
                ('standart', models.CharField(blank=True, default='FLOW_NFT', max_length=64, null=True)),
                ('token_id', models.PositiveIntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
